In [ ]:


# Telco Customer Churn Prediction:

In [1]:
import pandas as pd
import numpy as np

In [29]:
df = pd.read_csv('/content/Telco-Customer-Churn.csv')

In [30]:
df.head(3)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes

In [31]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [32]:
df.drop('customerID', axis =1, inplace = True)

In [33]:
df.head(3)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes

In [34]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [35]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [36]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    7043.000000  7043.000000     7043.000000   7032.000000
mean        0.162147    32.371149       64.761692   2283.300441
std         0.368612    24.559481       30.090047   2266.771362
min         0.000000     0.000000       18.250000     18.800000
25%         0.000000     9.000000       35.500000    401.450000
50%         0.000000    29.000000       70.350000   1397.475000
75%         0.000000    55.000000       89.850000   3794.737500
max         1.000000    72.000000      118.750000   8684.800000

In [13]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [37]:
df.shape

(7043, 20)

In [38]:
df = df.dropna(subset=['TotalCharges'])
df.reset_index(drop=True, inplace=True)

In [39]:
df.shape

(7032, 20)

In [ ]:
# DataPreprocessing

1. using Label encoder to convert categorical values to numerical values

In [41]:
from sklearn.preprocessing import LabelEncoder

cols = ['gender', 'Partner', 'Dependents','PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity','OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV','StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod','Churn']
d = {}

for i in cols:
  le = LabelEncoder()
  df[i] = le.fit_transform(df[i])

  classes = le.classes_
  print("classes",classes)

  map_d = dict(zip(classes, range(len(classes))))
  print("mapping",map_d)
  d.update(map_d)

classes ['Female' 'Male']
mapping {'Female': 0, 'Male': 1}
classes ['No' 'Yes']
mapping {'No': 0, 'Yes': 1}
classes ['No' 'Yes']
mapping {'No': 0, 'Yes': 1}
classes ['No' 'Yes']
mapping {'No': 0, 'Yes': 1}
classes ['No' 'No phone service' 'Yes']
mapping {'No': 0, 'No phone service': 1, 'Yes': 2}
classes ['DSL' 'Fiber optic' 'No']
mapping {'DSL': 0, 'Fiber optic': 1, 'No': 2}
classes ['No' 'No internet service' 'Yes']
mapping {'No': 0, 'No internet service': 1, 'Yes': 2}
classes ['No' 'No internet service' 'Yes']
mapping {'No': 0, 'No internet service': 1, 'Yes': 2}
classes ['No' 'No internet service' 'Yes']
mapping {'No': 0, 'No internet service': 1, 'Yes': 2}
classes ['No' 'No internet service' 'Yes']
mapping {'No': 0, 'No internet service': 1, 'Yes': 2}
classes ['No' 'No internet service' 'Yes']
mapping {'No': 0, 'No internet service': 1, 'Yes': 2}
classes ['No' 'No internet service' 'Yes']
mapping {'No': 0, 'No internet service': 1, 'Yes': 2}
classes ['Month-to-month' 'One year' 'Two year']
mapping {'Month-to-month': 0, 'One year': 1, 'Two year': 2}
classes ['No' 'Yes']
mapping {'No': 0, 'Yes': 1}
classes ['Bank transfer (automatic)' 'Credit card (automatic)' 'Electronic check'
 'Mailed check']
mapping {'Bank transfer (automatic)': 0, 'Credit card (automatic)': 1, 'Electronic check': 2, 'Mailed check': 3}
classes ['No' 'Yes']
mapping {'No': 0, 'Yes': 1}

In [42]:
df.head(5)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,29.85,0
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1889.50,0
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,108.15,1
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1840.75,0
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,151.65,1

In [ ]:
# Stadardisation: using Standard scaler
    # selecting feature, target column

In [43]:
x = df.iloc[:,0:-1]
y = df['Churn']

In [47]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

ft = ss.fit_transform(x)
x_df = pd.DataFrame(ft)
x_df.head(3)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,-1.009430,-0.440327,1.035617,-0.652305,-1.280248,-3.056334,0.062666,-1.183614,-0.917837,1.242875,-1.026988,-0.924267,-1.112632,-1.121501,-0.826735,0.828939,0.399805,-1.161694,-0.994194
1,0.990658,-0.440327,-0.965608,-0.652305,0.064303,0.327189,-0.991564,-1.183614,1.408012,-1.028998,1.245441,-0.924267,-1.112632,-1.121501,0.373926,-1.206361,1.336636,-0.260878,-0.173740
2,0.990658,-0.440327,-0.965608,-0.652305,-1.239504,0.327189,-0.991564,-1.183614,1.408012,1.242875,-1.026988,-0.924267,-1.112632,-1.121501,-0.826735,0.828939,1.336636,-0.363923,-0.959649

In [48]:
# Modeling:

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_df,y, test_size = 0.2,random_state = 30)

In [49]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((5625, 19), (1407, 19), (5625,), (1407,))

In [ ]:
# Classification problem

In [50]:
# Model 1 : Logistic Regression classifier


from sklearn.linear_model import LogisticRegression

m1 = LogisticRegression( class_weight='balanced')
m1.fit(x_train,y_train)

LogisticRegression(class_weight='balanced')

In [51]:
pred1 = m1.predict(x_test)
pred1

array([1, 0, 0, ..., 0, 1, 0])

In [105]:
#

from sklearn.metrics import accuracy_score, confusion_matrix,classification_report
accuracy_score(y_test,pred1)

0.749822316986496

In [106]:
print(classification_report(y_test,pred1))

              precision    recall  f1-score   support

           0       0.90      0.74      0.81      1031
           1       0.52      0.78      0.62       376

    accuracy                           0.75      1407
   macro avg       0.71      0.76      0.72      1407
weighted avg       0.80      0.75      0.76      1407

In [107]:
# Model 2: Desicion Tree Classifier

from sklearn.tree import DecisionTreeClassifier

m2 = DecisionTreeClassifier(class_weight='balanced',max_depth=10, min_samples_split=5, random_state=42)
m2.fit(x_train,y_train)

DecisionTreeClassifier(class_weight='balanced', max_depth=10,
                       min_samples_split=5, random_state=42)

In [108]:
pred2 = m2.predict(x_test)
pred2

array([1, 0, 0, ..., 0, 1, 0])

In [109]:
accuracy_score(y_test,pred2)

0.7277896233120114

In [110]:
print(classification_report(y_test,pred2))

              precision    recall  f1-score   support

           0       0.88      0.73      0.80      1031
           1       0.49      0.73      0.59       376

    accuracy                           0.73      1407
   macro avg       0.69      0.73      0.69      1407
weighted avg       0.78      0.73      0.74      1407

In [115]:
# Model 3: RandomForest Classifier

from sklearn.ensemble import RandomForestClassifier

m3  = RandomForestClassifier(class_weight='balanced',max_depth=12, min_samples_split=6, random_state=50)
m3.fit(x_train,y_train)

RandomForestClassifier(class_weight='balanced', max_depth=12,
                       min_samples_split=6, random_state=50)

In [116]:
pred3 = m3.predict(x_test)
pred3

array([1, 0, 0, ..., 0, 1, 0])

In [117]:
accuracy_score(y_test,pred3)

0.7889125799573561

In [118]:
print(classification_report(y_test,pred3))

              precision    recall  f1-score   support

           0       0.87      0.84      0.85      1031
           1       0.59      0.66      0.63       376

    accuracy                           0.79      1407
   macro avg       0.73      0.75      0.74      1407
weighted avg       0.80      0.79      0.79      1407

In [ ]:
# missing a customer who is likely to churn (a false
# negative) is more costly than mistakenly predicting churn for a customer who
# actually stays (a false positive).

# the best model is Logistic regression classifier with (recall = 0.78), meaning it's catching ~78% of churners